cluster:
  name: gha-created-cluster
  endpoint:
    addresses: 
     - https://34.122.242.223
    caCert: ./infra/ca.crt
    token: ./infra/token
  resources:
    frameworks:
      name: ["gha-policy"]
